### ISSUE TITLE
[Postman Support]: Not processing header defined in general authorization of Postman collection.

### ISSUE THREAD

**Issue by networkinss** [virtualansoftware/idaithalam#122]
The header that can be defined in a Postman collection for Authorization for all requests are not processed.
Those are added like the API Key authorization to all headers of all API request. 
Idaithalam is skipping them but should add them to all header of all requests.

**Comment by elans3** [comment]
@networkinss This issue already resolved. Can you confirm?

**Comment by networkinss** [comment]
Yes, it is fixed.
