### ISSUE TITLE
Excelcollection generator is called although it is Postman

### ISSUE THREAD

**Issue by oliverglas** [virtualansoftware/idaithalam#178]
I found a bracket error.
In class ParallelExecutor the check fails if there is an Excel input file.
It always resolves to true and tries to generate from an Excel file although the field inputexcel is Null.
That is because there is a missing bracket in the if statement for the or condition.
There the and is bound to the second or condition. 
The or condition must have brackets on their own to separate them from the and condition.
Here the correct brackets:

```
        if (((System.getenv("IDAITHALAM") == null
            || !"PROD".equalsIgnoreCase(System.getenv("IDAITHALAM")))
            && apiExecutorParam.getInputExcel() != null)) {
          ExcelToCollectionGenerator.createCollection(apiExecutorParam);
        } 
```

**Comment by elans3** [comment]
@networkinss  This issue already fixed.. Can you validate the same and close if it is completed.

**Comment by oliverglas** [comment]
Confirmed.
