### ISSUE TITLE
JSONObject Object check was not added

### ISSUE THREAD

**Issue by networkinss** [virtualansoftware/idaithalam#3]
If the response object is not found, it throws an exception.

**Comment by networkinss** [comment]
I fixed it in class 
io.virtualan.idaithalam.core.contract.validator.FeatureGenerationHelper
with a simply try catch.

    public static JSONArray createPosManToVirtualan(JSONObject object) {
        JSONArray virtualanArry = new JSONArray();
        if (object != null) {
            JSONArray arr = object.getJSONArray("item");
            if (arr != null && arr.length() > 0) {
                for (int i = 0; i < arr.length(); i++) {
                    try {
                        JSONArray responseArray = arr.getJSONObject(i).getJSONArray("response");
                        if (responseArray != null && responseArray.length()>0) {
                            for (int j = 0; j < responseArray.length(); j++) {
                                JSONObject virtualanObj = buildVirtualanObject(responseArray, j);
                                virtualanArry.put(virtualanObj);
                            }
                        }
                    }catch(Exception e) {
                        //continue loop.
                    }
                }
            }
        }
        return virtualanArry;
    }

**Comment by elans3** [comment]
I have to check the condition and need to few more handling as well. will update all changes and will deliver in the next release.

**Comment by elans3** [comment]
Object check was missed added. will resolve this issue.  New Version released 1.0.1

**Comment by elans3** [comment]
Version 1.0.5 released
